CREATE SCHEMA TODO;

-- Drop previously created tables.
DROP TABLE IF EXISTS TODO.TBUSER;
DROP TABLE IF EXISTS TODO.TBTODOLIST;
DROP TABLE IF EXISTS TODO.TBTODO;

-- User
CREATE TABLE TODO.TBUSER (
    USER_ID SERIAL NOT NULL,
    EMAIL VARCHAR(256) UNIQUE NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    CREATED TIMESTAMP NOT NULL
);

-- TodoList
CREATE TABLE TODO.TBTODOLIST (
    LIST_ID SERIAL NOT NULL,
    USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(256) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    LAST_MODIFIED TIMESTAMP NOT NULL
);

-- TodoList
CREATE TABLE TODO.TBTODO (
    TODO_ID SERIAL NOT NULL,
    LIST_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(256) NOT NULL,
    BODY VARCHAR(212),
    CREATED TIMESTAMP NOT NULL,
    LAST_MODIFIED TIMESTAMP NOT NULL
);

-- Primary keys
ALTER TABLE TODO.TBUSER ADD CONSTRAINT PKTBUSER PRIMARY KEY(USER_ID);
ALTER TABLE TODO.TBTODOLIST ADD CONSTRAINT PKTBTODOLIST PRIMARY KEY(USER_ID, LIST_ID);
ALTER TABLE TODO.TBTODO ADD CONSTRAINT PKTBTODO PRIMARY KEY(USER_ID, LIST_ID, TODO_ID);

-- Foreign keys
ALTER TABLE TODO.TBTODOLIST ADD CONSTRAINT FKLISTUSER FOREIGN KEY(USER_ID) REFERENCES TODO.TBUSER(USER_ID) ON DELETE CASCADE;
ALTER TABLE TODO.TBTODO ADD CONSTRAINT FKTODOLIST FOREIGN KEY(LIST_ID, USER_ID) REFERENCES TODO.TBTODOLIST(LIST_ID, USER_ID) ON DELETE CASCADE;
